blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Question & Support
    url: https://github.com/RevDra/human-face-detection/discussions
    about: Please ask questions here instead of opening an issue.
