name: Python Quality Check (Black, isort, Mypy, Flake8)

on: [push, pull_request]

permissions:
  contents: write

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tools
        run: pip install black isort mypy flake8

      - name: Run isort (Auto-fix)
        run: isort .

      - name: Run Black (Auto-format)
        run: black .

      - name: Check for changes and Commit
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "Bad code, fixing..."
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add .
            git commit -m "style: auto-fix imports (isort) and formatting (black)"
            git pull --rebase origin ${{ github.head_ref || github.ref_name }}       
            git push
          else
            echo "Nice code!"
          fi

      - name: Run Mypy (Type Check)
        run: mypy .

      - name: Run Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
